name: Reusable deploy
on: 
  workflow_call: 
    inputs:
      dist-file-path:
        required: true
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: dist-files
          path: ${{ inputs.dist-file-path }}
      - name: output information
        run: echo "Deploying & uploading"